paths:
  /inventory/item:
    get:
      tags:
        - Inventory
      summary: Retrieves an Item entry.
      description: |
        This will retrieve an Item entry.
      parameters:
        - in: query
          name: itemId
          description: The ID of the Item entry to retrieve.
          schema:
            type: string
        - in: query
          name: productCode
          description: The ID of the Item entry to retrieve.
          schema:
            type: string
      responses:
        200:
          description: Item data successfully retrieved.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    description: The message associated with this response.
                    type: string
                    example: Item data successfully retrieved.
                  data:
                    description: The data associated with this response.
                    type: object
                    properties:
                      project:
                        description: The project that the Item belongs to.
                        type: string
                      name:
                        description: The name of the Item.
                        type: string
                      ip:
                        description: The IP address of the Item.
                        type: string
                      type:
                        description: The connection type of the Item.
                        type: string
                        enum:
                          - LSM
                          - USM
                        example: LSM
                      username:
                        description: The username used to connect to the Item.
                        type: string
                      password:
                        description: The password used to connect to the Item.
                        type: string
                      createdAt:
                        description: The timestamp of when this Item object has been created.
                        type: string
                        format: date-time
                      updatedAt:
                        description: The timestamp of when this Item object has been updated.
                        type: string
                        format: date-time
        404:
          $ref: '#/components/responses/NotFoundError'
        500:
          $ref: '#/components/responses/InternalServerError'
